version: "3"
services:
  PyApp:
    image: sayhello
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "11055:80"
    networks:
      - pynet
  WebApp:
    image: webapp
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "11066:8080"
    networks:
      - webnet
networks:
  pynet:
  webnet: